import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:guardiago/features/salary/domain/shift_log.dart';
import 'package:guardiago/features/salary/domain/ot_calculator.dart';

/// Generates a read-only monthly salary audit report as PDF bytes, fully on
/// device. Intended to serve as evidence in an MOM wage dispute.
class PdfExportService {
  PdfExportService._();

  static Future<Uint8List> generateMonthlyReport({
    required List<ShiftLog> shifts,
    required List<OtResult> results,
    required int year,
    required int month,
    required String workerName,
  }) async {
    final pdf = pw.Document();

    final totalRegular = results.fold(0.0, (s, r) => s + r.regularPay);
    final totalOt = results.fold(0.0, (s, r) => s + r.otPay);
    final totalPay = totalRegular + totalOt;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'GuardianGo - Monthly Salary Audit Report',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Paragraph(
            text: 'Worker: $workerName\nPeriod: ${_monthName(month)} $year\n'
                'Generated: ${DateTime.now().toIso8601String()}\n'
                'This report is generated by GuardianGo based on Singapore '
                'Employment Act (Cap. 91). It serves as a record only.',
          ),
          pw.SizedBox(height: 12),
          pw.TableHelper.fromTextArray(
            headers: [
              'Date',
              'Clock In',
              'Clock Out',
              'Break',
              'Type',
              'Regular Pay',
              'OT Pay',
              'Total',
            ],
            data: List.generate(shifts.length, (i) {
              final s = shifts[i];
              final r = results[i];
              return [
                '${s.clockIn.day}/${s.clockIn.month}',
                _fmt(s.clockIn),
                _fmt(s.clockOut),
                '${s.breakMinutes}min',
                s.shiftType.name,
                '\$${r.regularPay.toStringAsFixed(2)}',
                '\$${r.otPay.toStringAsFixed(2)}',
                '\$${r.totalPay.toStringAsFixed(2)}',
              ];
            }),
          ),
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.black),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'SUMMARY',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(
                  'Total Regular Pay: \$${totalRegular.toStringAsFixed(2)}',
                ),
                pw.Text('Total OT Pay: \$${totalOt.toStringAsFixed(2)}'),
                pw.Text(
                  'Total Pay: \$${totalPay.toStringAsFixed(2)}',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 14,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'For disputes, contact MOM at 6438 5122 or mom.gov.sg',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static String _fmt(DateTime dt) =>
      '${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}';

  static String _monthName(int month) => const [
        '',
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ][month];
}
